### ISSUE TITLE
Expose doesn't work when source and target port are different

### ISSUE THREAD

**Issue by gtathub** [omrikiei/ktunnel#31] opened 2020-11-06 13:03 UTC
I tried to use the expose command to forward traffic from a kubernetes service to a local port:
```
ktunnel expose myservice 80:8000
```

Access from another pod in the same cluster using curl just says:
```
Failed to connect to myservice port 80: Connection refused
```

It looks like the service will be created with a source port of `80` and a target port of `8000`, but the pod is listening on port `80`. When I change the service manually and set source and target port to `80`, it works.

**Comment by omrikiei** [comment] 2020-11-15 17:07
What port is the local process listening to?

**Comment by omrikiei** [comment] 2020-11-15 18:39
Hello @gtathub, which port is your local machine listening on?

**Comment by luislhl** [comment] 2020-11-17 03:14
I'm having the same issue.

I have a service listening on port 3000 locally.
If I run `ktunnel expose my-service 8000:3000`, then I cannot access it from inside the cluster:
> curl: (7) Failed to connect to my-service port 8000: Connection refused

If I then run `ktunnel expose my-service 3000:3000`, it works.

**Comment by omrikiei** [comment] 2020-11-17 08:15
@luislhl @gtathub I'll try to look into it soon. thank you!

**Comment by gtathub** [comment] 2020-11-17 08:20
Hi @omrikiei,

I tried it with a simple python server running at port 8000.

`python3 -m http.server 8000`

As @luislhl points out, it works with same the source and target port. With different ports, I need to manually change the service to get it working.

**Comment by omrikiei** [comment] 2020-11-17 08:33
Hi @gtathub, it seems to be working for me
![image](https://user-images.githubusercontent.com/6465556/99365676-4a480d80-28c0-11eb-9285-ad03569fd115.png)

Which version of ktunnel are you using?

**Comment by gtathub** [comment] 2020-11-17 08:44
Hi @omrikiei,

ah, wait. You were testing the pod and used the port-forward to access port 3000 on the pod, right? I think the ports on the pod are fine. But can you also test the service that was created in Kubernetes by the expose command?

The service should have a different source and target port now (in your case source: 3000 and target: 8000). That means that another pod in the cluster that tries to use this service will be forward to your test pod on port 8000 and that leads to the `Connection refused` message.

**Comment by omrikiei** [comment] 2020-11-17 09:20
a fix will be available in ~20 minutes

**Comment by omrikiei** [comment] 2020-11-17 09:29
@gtathub @luislhl 
v1.3.1 with the fix is available through the releases page, and via homebrew.
could you kindly confirm the issue is resolved?

**Comment by gtathub** [comment] 2020-11-17 10:30
That solved the issue! Thank you!

**Comment by omrikiei** [comment] 2020-11-17 10:30
awesome, closing, thank you

**Closed by omrikiei** 2020-11-17 10:30 UTC
